name: medica
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  location: ^4.3.0
  telephony: ^0.1.4
  flutter_custom_clippers: ^2.0.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  google_fonts: ^2.1.0
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.17
  http:
  flutter_bluetooth_serial: ^0.4.0
  vibration: ^1.7.5
  audioplayers: ^1.0.1
  workmanager: ^0.4.1
  shared_preferences: ^2.0.15
  flutter_background: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

